displayLimit: 15
feedUrlArray:
  - https://zenn.dev/kinkinbeer135ml/feed
  - https://qiita.com/Landmaster135/feed.atom
  - https://www.endorphinbath.com/feed
  - https://us-central1-projectbeer15-37257.cloudfunctions.net/api/all
imgFileNameArray:
  - img/zenn.png
  - img/qiita.png
  - img/endorphinbath.png
  - img/note.png
sourceMarkdownFileName: README.md
postArea:
  start: <!--[START POSTS LIST]-->
  end: <!--[END POSTS LIST]-->
