displayLimit: 10
feedUrlArray:
  - https://zenn.dev/kinkinbeer135ml/feed
  - https://qiita.com/Landmaster135/feed.atom
  - https://www.endorphinbath.com/feed
imgFileNameArray:
  - img/zenn.png
  - img/qiita.png
  - img/endorphinbath.png
sourceMarkdownFileName: README.md
postArea:
  start: <!--[START POSTS LIST]-->
  end: <!--[END POSTS LIST]-->
