displayLimit: 5
feedUrlZenn: https://zenn.dev/kinkinbeer135ml/feed
feedUrlQiita: https://qiita.com/Landmaster135/feed.atom
feedUrlWordpress: https://www.endorphinbath.com/feed
sourceMarkdownFileName: README.md
