# name: Update README for Qiita/Zenn feed

# on:
#   workflow_dispatch:
#   schedule:
#     - cron:  '0 0 * * *'  

jobs:
  updateFeed:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up npm
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
    - run: npm install -y
    - run: npm test
    
    - name: Install feedFetcher
      run: npm install github.com/Landmaster135/feedFetcher@latest
    
    - name: run feedFetcher
      run: node ./node_modules/feedFetcher/bin/run --config-yaml=configOfFeedFetcher.yml
      
    - name: git setting
      run: |
        git config --local user.email "52403447+Landmaster135@users.noreply.github.com"
        git config --local user.name "Landmaster135"
    
    - name: git commit
      run: |
        git log -1
        git add README.md
        git diff --cached --quiet || (git commit -m "Update feed snippet" && git push origin main)
